apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: juiceshopname
  description: |
    Juiceshop from oawasp
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: lewislows/juice-shop
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: CNCF
  lifecycle: production
  definition:
    $file: ./api/openapi.yaml
